### ISSUE TITLE
关于compute shader光栅化大三角形问题

### ISSUE THREAD

**Issue by kyriewxcode** [happyfire/URasterizer#1]
compute shader光栅化阶段，每个三角形开一个thread，当镜头拉近的时候，三角形变得很大，导致开的thread数量减少，一个thread处理的像素过多，导致FPS降低非常明显。

不知道大佬有没有解决的办法，硬件对于这种是怎么实现的呢？
如果和UE5一样大三角形放到硬件中光栅化，Unity能否做到呢。。

**Comment by happyfire** [comment]
目前这种按三角形分配线程的方式必然有这个问题，所以这个方法只适用于小三角形。UE5应该也是对小三角形使用软光栅吧，因为他要解决的问题就是硬件光栅化微小表面效率低的问题。至于硬件光栅化，是有专门的Raster Engine，不是使用core来算。
另外也可以看下nvidia的这个：https://research.nvidia.com/sites/default/files/pubs/2011-08_High-Performance-Software-Rasterization/laine2011hpg_paper.pdf

**Comment by happyfire** [comment]
https://developer.nvidia.com/content/life-triangle-nvidias-logical-pipeline
这篇文章里讲了硬件处理光栅化的方式。根据三角形的包围框计算覆盖的屏幕Tile，将一个三角形分解为多个Tile内的部分，被多个GPC的Raster Engine并行处理。
如果要模拟这个做法，就不能直接分配线程去处理三角形了，而是先将三角形在屏幕内切分，然后分别同步处理。

**Comment by kyriewxcode** [comment]
> https://developer.nvidia.com/content/life-triangle-nvidias-logical-pipeline 这篇文章里讲了硬件处理光栅化的方式。根据三角形的包围框计算覆盖的屏幕Tile，将一个三角形分解为多个Tile内的部分，被多个GPC的Raster Engine并行处理。 如果要模拟这个做法，就不能直接分配线程去处理三角形了，而是先将三角形在屏幕内切分，然后分别同步处理。

可以的，其实和上面那一篇加 Bin rasterizer和 Coarse rasterizer 差不多，大的三角形可以这样处理（其实最好是能够扔给硬件处理，但是不会...），像素级的三角形就可以按照UE5的软光栅那样处理
